---
title: "What is the Cusine Food dataset"
author: "Bhasheyam"
date: "13 December 2017"
output: html_document
---

Read the data from the file

```{r}
library(rjson)
cookdata = fromJSON(file = "train.json")
cooktest = fromJSON(file = "test.json")
head(cookdata)
```
Result Preparation


```{r}
id = c()
for ( datat in cooktest){
   id = c(id,datat$id)
}
resultcook = as.data.frame(id)

```

Find all the Cusine in the list find the ingredients used in the cusine.
```{r}
cusinel = c()
alllist = c()
for ( data1 in cookdata){
      alllist = c(alllist,data1$cuisine)
  
    if (data1$cuisine %in% cusinel){
      
    }
    else{
      temp = c(data1$cuisine)
      
      cusinel =c(cusinel,temp)
    }
 
  
}


```



```{r}
table(alllist)
```

```{r}
cusinel
```



```{r}
n = length(cusinel)
cusinelistrep =list()
for (i in 1:n){
  cusinelistrep[[cusinel[i]]]=c()
  
}


```

```{r}
for(cooks in cookdata){
  for (ingredients in cooks$ingredients){
    
      cusinelistrep[[cooks$cuisine]] = c( cusinelistrep[[cooks$cuisine]], ingredients)
    
    
  }
  
  
}


```

```{r}
for (addi in cusinel){tempp =table(cusinelistrep[[addi]])
}
tempp[names(tempp)=="allspice"] + 1
```




Now we have the list of cusine, so lets make a list for all cusine with ingredients


```{r}
ingredientsall = c()
for(cooks in cookdata){
  for (ingredients in cooks$ingredients){
    if (ingredients %in% ingredientsall){
      
    }
    else{
      ingredientsall = c( ingredientsall, ingredients)
    }
    
  }
  
  
}
traincook = as.data.frame(ingredientsall)
fix(traincook)
newt = t(traincook)
fix(newt)
```




```{r}
maxdoc = 18

for (addin in cusinel){
  
   countdoc = length(cusinelistrep[[addin]])
   temp =table(cusinelistrep[[addin]])
   templist = c()
   for (onein in ingredientsall){
     
  
  total = 0
  
  
   }
}

```

























```{r}
n = length(cusinel)

cusinelist1 =list()
processlist = list()
for (i in 1:n){
 
  cusinelist1[[cusinel[i]]]=c()
  processlist[[cusinel[i]]] =c()
  
}
cusinelist1


```


```{r}
for(cooks in cookdata){
  for (ingredients in cooks$ingredients){
    if (ingredients %in% cusinelist1[[cooks$cuisine]]){
      
    }
    else{
    
      cusinelist1[[cooks$cuisine]] = c( cusinelist1[[cooks$cuisine]], ingredients)
    }
    
  }
  
  
}


names(cusinelist1)
```



Remove data which are in almost more than 3 cusine
```{r}
length(cusinelist1[["russian"]])
max = 14

checkcount = function(word){
  temp = 0
  for (lis1 in cusinelist1){
    
    if ( word %in% lis1){
       temp = temp + 1
    }
    
  }
  if (temp<= max){
    return(TRUE)
  }
  return (FALSE)
}

n = length(cusinel)

for (ii in 1:n){
  for ( ind in cusinelist1[[cusinel[ii]]]){
     if(checkcount(ind)){
      
       processlist[[cusinel[ii]]] = c(processlist[[cusinel[ii]]],ind)
     }
  }
}
length(cusinelist1[["indian"]])
length(processlist[["indian"]])
```








```{r}
countin = function(lis123,ingreds){
  value = 0
  for ( in1 in ingreds){
    if (in1 %in% lis123){
      value = value + 1
    }
    
  }
  return (value)
}
cookres =c()
for (cookst in cooktest){
  max = 0
  res = ""
  for(name in names(processlist)){
    
    temp = countin(processlist[[name]],cookst$ingredients)
    if( max < temp){
      max = temp
      res = name
    }
  }
  if (res == ""){
    cookres = c(cookres,"japanese")
  }
  else{
    cookres = c(cookres,res)
    
  }
  
 
}
resultcook$cuisine = cookres

fix(resultcook)

table(cookres)
```

Here the Accuracy is very low as we see only support count ., which is not a best way to follow
```{r}
write.csv(resultcook, file = "Submisioncooklast.csv", row.names = FALSE)
```
```


 
    
  
```{r}

```









